#!/bin/csh
#$ -N RoundUp
#$ -e {5}
#$ -o {5}
#$ -l ct=24:00:00
#$ -l fsize=4096M
#$ -l sps=1
#$ -l xrootd=1
#$ -l mem_free=4096M
#$ -l s_rss=4096M
#$ -p 0
#$ -l os=sl6
#$ -P P_hess -cwd

source /afs/in2p3.fr/throng/hess/HESS_Soft_0-8-32/env.csh
awk 'BEGIN {srand();random=int(rand()*120); print random}' | xargs sleep

if ( ! $?TMPDIR ) setenv TMPDIR `pwd`

if ( ! $?TMPBATCH ) setenv TMPBATCH $TMPDIR

unsetenv HPSS
setenv XROOTD root://ccxroot:1999//hpss/in2p3.fr/group/hess
setenv CALIB_PATH /sps/hess/prod/Calibration
setenv SPECTRUM_PATH /sps/hess/prod/SpectrumTables/HESS_Soft_0-8-32_HESSII_Prod8
setenv DST_XROOTD_PATH root://ccxroot:1999//hpss/in2p3.fr/group/hess/DST

cd $TMPBATCH

cat > make_ModelPlus_Mono_Std_run.C  << EOF
void make_ModelPlus_Mono_Std_run(unsigned runno)
{
if(gROOT->IsBatch())
  gSystem->Load("libGui.so");
gROOT->SetStyle("Plain");
gStyle->SetOptFit(111);
gStyle->SetPalette(1);
//===================
// = Analysis 
gSystem->Load("librootparisanalysis.so");
gSystem->Load("librootparisrunquality.so");
gSystem->Load("librootparisanalysisCommon.so");
gSystem->Load("librootparisanalysis_scripts.so");
//=============================================

//===================
// = Path 
use_analysis();
set_verbose(false);
set_chain_name("ModelPlus_Mono_Std");
//===================
// = Analysis Setup
use_model_mono_analysis();
set_model_mono_name("Mono");
fill_likelihood_monitor(1);
save_likelihood_monitor(0);
set_prefered_reconstruction("ModelMono");
//===================
// = DST Config
set_dst_type(SashFile::DST_Model);
set_dst_version("Model_HESSII_Hybrid_Prod8");
set_dst_subconfig("DEFAULT");
//===================
// = Shape Cuts
set_chargemin("ModelMono",60,Sash::TelescopeConfig::HESS2_2048);
set_nomdistance_range("ModelMono",0,1.4, Sash::TelescopeConfig::HESS2_2048);
set_min_containment("ModelMono",0.5,Sash::TelescopeConfig::HESS2_2048);
set_min_pixelsabove5pe("ModelMono",5,Sash::TelescopeConfig::HESS2_2048);
//===================
// = Target 
set_radec();
set_target("{0}",{1},{2});
//===================
// = Run List 
set_run({3});
//===================
// = Regions
set_excludedregion_size(0.25);
//===================
// = Plots 
add_plot("MeanScaledShowerGoodness",150,-5,10,ParisAnalysis::Event_PreSelected,"",1);
add_plot("MeanScaledShowerGoodnessUnCorrected",150,-5,10,ParisAnalysis::Event_PreSelected,"",1);
add_plot("MeanScaledBackgroundGoodness",150,-5,10,ParisAnalysis::Event_PreSelected,"",1);
add_plot("MeanScaledPedestalGoodness",150,-5,10,ParisAnalysis::Event_PreSelected,"",1);
add_plot("MeanScaledShowerGoodness",150,-5,10,ParisAnalysis::Event_Classified,"",1);
add_plot("MeanScaledShowerGoodnessUnCorrected",150,-5,10,ParisAnalysis::Event_Classified,"",1);
add_plot("MeanScaledBackgroundGoodness",150,-5,10,ParisAnalysis::Event_Classified,"",1);
add_plot("MeanScaledPedestalGoodness",150,-5,10,ParisAnalysis::Event_Classified,"",1);
add_plot("MeanScaledShowerGoodness",150,-5,10,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("MeanScaledShowerGoodnessUnCorrected",150,-5,10,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("MeanScaledBackgroundGoodness",150,-5,10,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("MeanScaledPedestalGoodness",150,-5,10,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("MeanScaledShowerGoodnessLinear",150,-5,10,ParisAnalysis::Event_Classified,"",1);
add_plot("MeanScaledShowerGoodnessLinearUnCorrected",150,-5,10,ParisAnalysis::Event_Classified,"",1);
add_plot("MeanScaledBackgroundGoodnessLinear",150,-5,10,ParisAnalysis::Event_Classified,"",1);
add_plot("MeanScaledPedestalGoodnessLinear",150,-5,10,ParisAnalysis::Event_Classified,"",1);
add_plot("MeanScaledShowerGoodnessLinear",150,-5,10,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("MeanScaledShowerGoodnessLinearUnCorrected",150,-5,10,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("MeanScaledBackgroundGoodnessLinear",150,-5,10,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("MeanScaledPedestalGoodnessLinear",150,-5,10,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("PrimaryDepth",60,-2,10,ParisAnalysis::Event_PreSelected,"",1);
add_plot("PrimaryDepth",60,-2,10,ParisAnalysis::Event_Classified,"",1);
add_plot("PrimaryDepth",60,-2,10,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("AbsoluteEfficiency",50,0,2,ParisAnalysis::Event_Classified,"",1);
add_plot("AbsoluteEfficiency",50,0,2,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("MeanScaledShowerGoodnessToM",150,-10,10,ParisAnalysis::Event_PreSelected,"",1);
add_plot("MeanScaledShowerGoodnessToMUnCorrected",150,-10,10,ParisAnalysis::Event_PreSelected,"",1);
add_plot("MeanScaledShowerGoodnessToM",150,-10,10,ParisAnalysis::Event_Classified,"",1);
add_plot("MeanScaledShowerGoodnessToMUnCorrected",150,-10,10,ParisAnalysis::Event_Classified,"",1);
add_plot("MeanScaledShowerGoodnessToM",150,-10,10,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("MeanScaledShowerGoodnessToMUnCorrected",150,-10,10,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("MeanScaledShiftedShowerGoodnessToM",150,-10,10,ParisAnalysis::Event_PreSelected,"",1);
add_plot("MeanScaledShiftedShowerGoodnessToMUnCorrected",150,-10,10,ParisAnalysis::Event_PreSelected,"",1);
add_plot("MeanScaledShiftedShowerGoodnessToM",150,-10,10,ParisAnalysis::Event_Classified,"",1);
add_plot("MeanScaledShiftedShowerGoodnessToMUnCorrected",150,-10,10,ParisAnalysis::Event_Classified,"",1);
add_plot("MeanScaledShiftedShowerGoodnessToM",150,-10,10,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("MeanScaledShiftedShowerGoodnessToMUnCorrected",150,-10,10,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("MeanScaledEvtShiftedShowerGoodnessToM",150,-10,10,ParisAnalysis::Event_PreSelected,"",1);
add_plot("MeanScaledEvtShiftedShowerGoodnessToMUnCorrected",150,-10,10,ParisAnalysis::Event_PreSelected,"",1);
add_plot("MeanScaledEvtShiftedShowerGoodnessToM",150,-10,10,ParisAnalysis::Event_Classified,"",1);
add_plot("MeanScaledEvtShiftedShowerGoodnessToMUnCorrected",150,-10,10,ParisAnalysis::Event_Classified,"",1);
add_plot("MeanScaledEvtShiftedShowerGoodnessToM",150,-10,10,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("MeanScaledEvtShiftedShowerGoodnessToMUnCorrected",150,-10,10,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("MeanScaledShowerGoodnessFull",150,-10,10,ParisAnalysis::Event_PreSelected,"",1);
add_plot("MeanScaledShowerGoodnessFullUnCorrected",150,-10,10,ParisAnalysis::Event_PreSelected,"",1);
add_plot("MeanScaledShowerGoodnessFull",150,-10,10,ParisAnalysis::Event_Classified,"",1);
add_plot("MeanScaledShowerGoodnessFullUnCorrected",150,-10,10,ParisAnalysis::Event_Classified,"",1);
add_plot("MeanScaledShowerGoodnessFull",150,-10,10,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("MeanScaledShowerGoodnessFullUnCorrected",150,-10,10,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("MeanScaledShiftedShowerGoodnessFull",150,-10,10,ParisAnalysis::Event_PreSelected,"",1);
add_plot("MeanScaledShiftedShowerGoodnessFullUnCorrected",150,-10,10,ParisAnalysis::Event_PreSelected,"",1);
add_plot("MeanScaledShiftedShowerGoodnessFull",150,-10,10,ParisAnalysis::Event_Classified,"",1);
add_plot("MeanScaledShiftedShowerGoodnessFullUnCorrected",150,-10,10,ParisAnalysis::Event_Classified,"",1);
add_plot("MeanScaledShiftedShowerGoodnessFull",150,-10,10,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("MeanScaledShiftedShowerGoodnessFullUnCorrected",150,-10,10,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("MeanScaledEvtShiftedShowerGoodnessFull",150,-10,10,ParisAnalysis::Event_PreSelected,"",1);
add_plot("MeanScaledEvtShiftedShowerGoodnessFullUnCorrected",150,-10,10,ParisAnalysis::Event_PreSelected,"",1);
add_plot("MeanScaledEvtShiftedShowerGoodnessFull",150,-10,10,ParisAnalysis::Event_Classified,"",1);
add_plot("MeanScaledEvtShiftedShowerGoodnessFullUnCorrected",150,-10,10,ParisAnalysis::Event_Classified,"",1);
add_plot("MeanScaledEvtShiftedShowerGoodnessFull",150,-10,10,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("MeanScaledEvtShiftedShowerGoodnessFullUnCorrected",150,-10,10,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("NSBLikelihood",220,-10,2,ParisAnalysis::Event_PreSelected,"",1);
add_plot("NSBLikelihood",220,-10,2,ParisAnalysis::Event_Classified,"",1);
add_plot("NSBLikelihood",220,-10,2,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("UniformNSBLikelihood",220,-10,2,ParisAnalysis::Event_PreSelected,"",1);
add_plot("UniformNSBLikelihood",220,-10,2,ParisAnalysis::Event_Classified,"",1);
add_plot("UniformNSBLikelihood",220,-10,2,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("MeanScaledNSBLikelihood",100,-10,10,ParisAnalysis::Event_PreSelected,"",1);
add_plot("MeanScaledNSBLikelihood",100,-10,10,ParisAnalysis::Event_Classified,"",1);
add_plot("MeanScaledNSBLikelihood",100,-10,10,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("MeanScaledUniformNSBLikelihood",100,-10,10,ParisAnalysis::Event_PreSelected,"",1);
add_plot("MeanScaledUniformNSBLikelihood",100,-10,10,ParisAnalysis::Event_Classified,"",1);
add_plot("MeanScaledUniformNSBLikelihood",100,-10,10,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("ConditionNumber",60,0,6,ParisAnalysis::Event_PreSelected,"",1);
add_plot("ConditionNumber",60,0,6,ParisAnalysis::Event_Classified,"",1);
add_plot("ConditionNumber",60,0,6,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("NSBGoodness",100,-5,60,ParisAnalysis::Event_PreSelected,"",1);
add_plot("NSBGoodness",100,-5,60,ParisAnalysis::Event_Classified,"",1);
add_plot("NSBGoodness",100,-5,60,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("ShowerNSBGoodness",100,-5,60,ParisAnalysis::Event_PreSelected,"",1);
add_plot("ShowerNSBGoodness",100,-5,60,ParisAnalysis::Event_Classified,"",1);
add_plot("ShowerNSBGoodness",100,-5,60,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("MeanScaledNSBGoodness",100,-20,10,ParisAnalysis::Event_PreSelected,"",1);
add_plot("MeanScaledNSBGoodness",100,-20,10,ParisAnalysis::Event_Classified,"",1);
add_plot("MeanScaledNSBGoodness",100,-20,10,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("MeanScaledShowerNSBGoodness",100,-10,10,ParisAnalysis::Event_PreSelected,"",1);
add_plot("MeanScaledShowerNSBGoodness",100,-10,10,ParisAnalysis::Event_Classified,"",1);
add_plot("MeanScaledShowerNSBGoodness",100,-10,10,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("UniformNSBGoodness",100,0,200,ParisAnalysis::Event_PreSelected,"",1);
add_plot("UniformNSBGoodness",100,0,200,ParisAnalysis::Event_Classified,"",1);
add_plot("UniformNSBGoodness",100,0,200,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("ShowerUniformNSBGoodness",100,-100,1000,ParisAnalysis::Event_PreSelected,"",1);
add_plot("ShowerUniformNSBGoodness",100,-100,1000,ParisAnalysis::Event_Classified,"",1);
add_plot("ShowerUniformNSBGoodness",100,-100,1000,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("MeanScaledUniformNSBGoodness",200,-50,100,ParisAnalysis::Event_PreSelected,"",1);
add_plot("MeanScaledUniformNSBGoodness",200,-50,100,ParisAnalysis::Event_Classified,"",1);
add_plot("MeanScaledUniformNSBGoodness",200,-50,100,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("MeanScaledShowerUniformNSBGoodness",200,-20,200,ParisAnalysis::Event_PreSelected,"",1);
add_plot("MeanScaledShowerUniformNSBGoodness",200,-20,200,ParisAnalysis::Event_Classified,"",1);
add_plot("MeanScaledShowerUniformNSBGoodness",200,-20,200,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("NSBGoodnessUnCorr",100,-5,60,ParisAnalysis::Event_PreSelected,"",1);
add_plot("NSBGoodnessUnCorr",100,-5,60,ParisAnalysis::Event_Classified,"",1);
add_plot("NSBGoodnessUnCorr",100,-5,600,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("ShowerNSBGoodnessToM",100,-50,1000,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("ShowerNSBGoodnessToM",100,-50,1000,ParisAnalysis::Event_Classified,"",1);
add_plot("ShowerNSBGoodnessToM",100,-50,1000,ParisAnalysis::Event_PreSelected,"",1);
add_plot("ShowerNSBGoodnessFull",100,-50,1000,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("ShowerNSBGoodnessFull",100,-50,1000,ParisAnalysis::Event_Classified,"",1);
add_plot("ShowerNSBGoodnessFull",100,-50,1000,ParisAnalysis::Event_PreSelected,"",1);
add_plot("ShowerUniformNSBGoodnessFull",100,-50,1000,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("ShowerUniformNSBGoodnessFull",100,-50,1000,ParisAnalysis::Event_Classified,"",1);
add_plot("ShowerUniformNSBGoodnessFull",100,-50,1000,ParisAnalysis::Event_PreSelected,"",1);
add_plot("MeanScaledShowerNSBGoodnessToM",100,-20,50,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("MeanScaledShowerNSBGoodnessToM",100,-20,50,ParisAnalysis::Event_Classified,"",1);
add_plot("MeanScaledShowerNSBGoodnessToM",100,-20,50,ParisAnalysis::Event_PreSelected,"",1);
add_plot("MeanScaledShowerNSBGoodnessFull",200,-20,200,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("MeanScaledShowerNSBGoodnessFull",200,-20,200,ParisAnalysis::Event_Classified,"",1);
add_plot("MeanScaledShowerNSBGoodnessFull",200,-20,200,ParisAnalysis::Event_PreSelected,"",1);
add_plot("MeanScaledShowerUniformNSBGoodnessFull",200,-20,300,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("MeanScaledShowerUniformNSBGoodnessFull",200,-20,300,ParisAnalysis::Event_Classified,"",1);
add_plot("MeanScaledShowerUniformNSBGoodnessFull",200,-20,300,ParisAnalysis::Event_PreSelected,"",1);
add_plot("NSBGoodness","NSBLikelihood",100,-5,60,60,-10,2,ParisAnalysis::Event_PreSelected,"","",1);
add_plot("NSBGoodness","NSBLikelihood",100,-5,60,60,-10,2,ParisAnalysis::Event_Classified,"","",1);
add_plot("NSBGoodness","NSBLikelihood",100,-5,60,60,-10,2,ParisAnalysis::Event_GammaCandidate,"","",1);
add_telescope_plot("TelLogCharge","DirectionError",200,1.5,4,50,0,0.2,ParisAnalysis::Event_PreSelected,false,"","",ParisAnalysis::Tel_Selected,1);
add_telescope_plot("TelLogCharge","DirectionError",200,1.5,4,50,0,0.2,ParisAnalysis::Event_Classified,false,"","",ParisAnalysis::Tel_Selected,1);
add_telescope_plot("TelLogCharge","DirectionError",200,1.5,4,50,0,0.2,ParisAnalysis::Event_GammaCandidate,false,"","",ParisAnalysis::Tel_Selected,1);
add_telescope_plot("TelLogCharge","CoreSq2",200,1.5,4,50,0,100000,ParisAnalysis::Event_PreSelected,false,"","",ParisAnalysis::Tel_Selected,1);
add_telescope_plot("TelLogCharge","CoreSq2",200,1.5,4,50,0,100000,ParisAnalysis::Event_Classified,false,"","",ParisAnalysis::Tel_Selected,1);
add_telescope_plot("TelLogCharge","CoreSq2",200,1.5,4,50,0,100000,ParisAnalysis::Event_GammaCandidate,false,"","",ParisAnalysis::Tel_Selected,1);
add_telescope_plot("TelLogCharge","MeanScaledShowerGoodness",200,1.5,4,150,-5,10,ParisAnalysis::Event_PreSelected,false,"","",ParisAnalysis::Tel_Selected,1);
add_telescope_plot("TelLogCharge","MeanScaledShowerGoodness",200,1.5,4,150,-5,10,ParisAnalysis::Event_Classified,false,"","",ParisAnalysis::Tel_Selected,1);
add_telescope_plot("TelLogCharge","MeanScaledShowerGoodness",200,1.5,4,150,-5,10,ParisAnalysis::Event_GammaCandidate,false,"","",ParisAnalysis::Tel_Selected,1);
add_plot("NSBGoodnessUnCorr","NSBLikelihood",100,-5,60,60,-10,2,ParisAnalysis::Event_PreSelected,"","",1);
add_plot("NSBGoodnessUnCorr","NSBLikelihood",100,-5,60,60,-10,2,ParisAnalysis::Event_Classified,"","",1);
add_plot("NSBGoodnessUnCorr","NSBLikelihood",100,-5,60,60,-10,2,ParisAnalysis::Event_GammaCandidate,"","",1);
add_plot("ShowerNSBLikelihood",50,-500,0,ParisAnalysis::Event_PreSelected,"",1);
add_plot("ShowerNSBLikelihood",50,-500,0,ParisAnalysis::Event_Classified,"",1);
add_plot("ShowerNSBLikelihood",50,-500,0,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("MeanScaledShowerNSBLikelihood",1000,-500,500,ParisAnalysis::Event_PreSelected,"",1);
add_plot("MeanScaledShowerNSBLikelihood",1000,-500,500,ParisAnalysis::Event_Classified,"",1);
add_plot("MeanScaledShowerNSBLikelihood",1000,-500,500,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("MeanScaledShowerUniformNSBLikelihood",1000,-500,500,ParisAnalysis::Event_PreSelected,"",1);
add_plot("MeanScaledShowerUniformNSBLikelihood",1000,-500,500,ParisAnalysis::Event_Classified,"",1);
add_plot("MeanScaledShowerUniformNSBLikelihood",1000,-500,500,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("NSBLikelihood","ShowerNSBLikelihood",60,-10,2,50,-500,0,ParisAnalysis::Event_PreSelected,"","",1);
add_plot("NSBLikelihood","ShowerNSBLikelihood",60,-10,2,50,-500,0,ParisAnalysis::Event_Classified,"","",1);
add_plot("NSBLikelihood","ShowerNSBLikelihood",60,-10,2,50,-500,0,ParisAnalysis::Event_GammaCandidate,"","",1);
add_plot("DirectionError",50,0,0.6,ParisAnalysis::Event_PreSelected,"",1);
add_plot("DirectionError",50,0,0.6,ParisAnalysis::Event_Classified,"",1);
add_plot("DirectionError",50,0,0.6,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("MeanScaledModelShowerGoodness",150,-5,10,ParisAnalysis::Event_Classified,"",1);
add_plot("MeanScaledModelShowerGoodness",150,-5,10,ParisAnalysis::Event_GammaCandidate,"",1);
add_plot("MeanScaledDiffShowerGoodness",150,-5,10,ParisAnalysis::Event_Classified,"",1);
add_plot("MeanScaledDiffShowerGoodness",150,-5,10,ParisAnalysis::Event_GammaCandidate,"",1);
add_telescope_plot("TelLogModelCharge",100,1.5,4,ParisAnalysis::Event_Classified,false,"",ParisAnalysis::Tel_Selected,1);
add_telescope_plot("TelLogModelCharge",100,1.5,4,ParisAnalysis::Event_GammaCandidate,false,"",ParisAnalysis::Tel_Selected,1);
add_telescope_plot("TelLogShowerModelCharge",100,1.5,4,ParisAnalysis::Event_Classified,false,"",ParisAnalysis::Tel_Selected,1);
add_telescope_plot("TelLogShowerModelCharge",100,1.5,4,ParisAnalysis::Event_GammaCandidate,false,"",ParisAnalysis::Tel_Selected,1);
add_telescope_plot("TelDeltaCOGR",100,0,2,ParisAnalysis::Event_PreSelected,false,"",ParisAnalysis::Tel_Selected,1);
add_telescope_plot("TelDeltaCOGR",100,0,2,ParisAnalysis::Event_Classified,false,"",ParisAnalysis::Tel_Selected,1);
add_telescope_plot("TelDeltaCOGR",100,0,2,ParisAnalysis::Event_GammaCandidate,false,"",ParisAnalysis::Tel_Selected,1);
add_telescope_plot("TelNPixelsAbove2PE",100,0,100,ParisAnalysis::Event_PreSelected,false,"",ParisAnalysis::Tel_Selected,1);
add_telescope_plot("TelNPixelsAbove2PE",100,0,100,ParisAnalysis::Event_Classified,false,"",ParisAnalysis::Tel_Selected,1);
add_telescope_plot("TelNPixelsAbove2PE",100,0,100,ParisAnalysis::Event_GammaCandidate,false,"",ParisAnalysis::Tel_Selected,1);
add_telescope_plot("TelNPixelsAbove3PE",100,0,100,ParisAnalysis::Event_PreSelected,false,"",ParisAnalysis::Tel_Selected,1);
add_telescope_plot("TelNPixelsAbove3PE",100,0,100,ParisAnalysis::Event_Classified,false,"",ParisAnalysis::Tel_Selected,1);
add_telescope_plot("TelNPixelsAbove3PE",100,0,100,ParisAnalysis::Event_GammaCandidate,false,"",ParisAnalysis::Tel_Selected,1);
add_telescope_plot("TelNPixelsAbove4PE",100,0,100,ParisAnalysis::Event_PreSelected,false,"",ParisAnalysis::Tel_Selected,1);
add_telescope_plot("TelNPixelsAbove4PE",100,0,100,ParisAnalysis::Event_Classified,false,"",ParisAnalysis::Tel_Selected,1);
add_telescope_plot("TelNPixelsAbove4PE",100,0,100,ParisAnalysis::Event_GammaCandidate,false,"",ParisAnalysis::Tel_Selected,1);
add_telescope_plot("TelNPixelsAbove5PE",100,0,100,ParisAnalysis::Event_Reconstructed,false,"",ParisAnalysis::Tel_Selected,1);
add_telescope_plot("TelNPixelsAbove5PE",100,0,100,ParisAnalysis::Event_PreSelected,false,"",ParisAnalysis::Tel_Selected,1);
add_telescope_plot("TelNPixelsAbove5PE",100,0,100,ParisAnalysis::Event_Classified,false,"",ParisAnalysis::Tel_Selected,1);
add_telescope_plot("TelNPixelsAbove5PE",100,0,100,ParisAnalysis::Event_GammaCandidate,false,"",ParisAnalysis::Tel_Selected,1);
add_telescope_plot("TelNPixelsAbove10PE",100,0,100,ParisAnalysis::Event_PreSelected,false,"",ParisAnalysis::Tel_Selected,1);
add_telescope_plot("TelNPixelsAbove10PE",100,0,100,ParisAnalysis::Event_Classified,false,"",ParisAnalysis::Tel_Selected,1);
add_telescope_plot("TelNPixelsAbove10PE",100,0,100,ParisAnalysis::Event_GammaCandidate,false,"",ParisAnalysis::Tel_Selected,1);
add_sky_plot("NSBLikelihood",ParisAnalysis::Event_Classified,"");
add_sky_plot("NSBLikelihood",ParisAnalysis::Event_GammaCandidate,"");
add_sky_plot("DirectionError",ParisAnalysis::Event_Classified,"");
add_sky_plot("DirectionError",ParisAnalysis::Event_GammaCandidate,"");
add_sky_plot("MeanScaledShowerGoodness",ParisAnalysis::Event_Classified,"");
add_sky_plot("MeanScaledShowerGoodness",ParisAnalysis::Event_GammaCandidate,"");
add_sky_plot("MeanScaledModelShowerGoodness",ParisAnalysis::Event_Classified,"");
add_sky_plot("MeanScaledModelShowerGoodness",ParisAnalysis::Event_GammaCandidate,"");
add_fov_plot("NSBLikelihood",ParisAnalysis::Event_Classified,"");
add_fov_plot("NSBLikelihood",ParisAnalysis::Event_GammaCandidate,"");
add_fov_plot("ShowerNSBLikelihood",ParisAnalysis::Event_Classified,"");
add_fov_plot("ShowerNSBLikelihood",ParisAnalysis::Event_GammaCandidate,"");
add_fov_plot("DirectionError",ParisAnalysis::Event_Classified,"");
add_fov_plot("DirectionError",ParisAnalysis::Event_GammaCandidate,"");
add_fov_plot("MeanScaledShowerGoodness",ParisAnalysis::Event_Classified,"");
add_fov_plot("MeanScaledShowerGoodness",ParisAnalysis::Event_GammaCandidate,"");
add_fov_plot("MeanScaledModelShowerGoodness",ParisAnalysis::Event_Classified,"");
add_fov_plot("MeanScaledModelShowerGoodness",ParisAnalysis::Event_GammaCandidate,"");
add_fov_plot("MeanScaledBackgroundGoodness",ParisAnalysis::Event_Classified,"");
add_fov_plot("MeanScaledBackgroundGoodness",ParisAnalysis::Event_GammaCandidate,"");
add_fov_plot("MeanScaledPedestalGoodness",ParisAnalysis::Event_Classified,"");
add_fov_plot("MeanScaledPedestalGoodness",ParisAnalysis::Event_GammaCandidate,"");
add_fov_plot("ShowerGoodness",ParisAnalysis::Event_Classified,"");
add_fov_plot("ShowerGoodness",ParisAnalysis::Event_GammaCandidate,"");
add_fov_plot("ModelShowerGoodness",ParisAnalysis::Event_Classified,"");
add_fov_plot("ModelShowerGoodness",ParisAnalysis::Event_GammaCandidate,"");
add_fov_plot("Goodness",ParisAnalysis::Event_Classified,"");
add_fov_plot("Goodness",ParisAnalysis::Event_GammaCandidate,"");
add_fov_plot("LogEnergy",ParisAnalysis::Event_Classified,"");
add_fov_plot("LogEnergy",ParisAnalysis::Event_GammaCandidate,"");
add_fov_plot("PrimaryDepth",ParisAnalysis::Event_Classified,"");
add_fov_plot("PrimaryDepth",ParisAnalysis::Event_GammaCandidate,"");
add_fov_plot("AbsoluteEfficiency",ParisAnalysis::Event_Classified,"");
add_fov_plot("AbsoluteEfficiency",ParisAnalysis::Event_GammaCandidate,"");
add_plot("MeanScaledShowerGoodness","MeanScaledModelShowerGoodness",150,-5,10,150,-5,10,ParisAnalysis::Event_Classified,"","",1);
add_telescope_scaled_plot("COGX","COGY","TelDeltaCOGX",ParisAnalysis::Event_PreSelected,false,"","","",ParisAnalysis::Tel_Selected,0);
add_telescope_scaled_plot("COGX","COGY","TelDeltaCOGY",ParisAnalysis::Event_PreSelected,false,"","","",ParisAnalysis::Tel_Selected,0);
add_telescope_scaled_plot("COGX","COGY","TelDeltaCOGX",ParisAnalysis::Event_Classified,false,"","","",ParisAnalysis::Tel_Selected,0);
add_telescope_scaled_plot("COGX","COGY","TelDeltaCOGY",ParisAnalysis::Event_Classified,false,"","","",ParisAnalysis::Tel_Selected,0);
add_telescope_scaled_plot("COGX","COGY","TelDeltaCOGX",ParisAnalysis::Event_GammaCandidate,false,"","","",ParisAnalysis::Tel_Selected,0);
add_telescope_scaled_plot("COGX","COGY","TelDeltaCOGY",ParisAnalysis::Event_GammaCandidate,false,"","","",ParisAnalysis::Tel_Selected,0);
add_telescope_scaled_plot("COGX","COGY","TelDeltaCOGR",ParisAnalysis::Event_PreSelected,false,"","","",ParisAnalysis::Tel_Selected,0);
add_telescope_scaled_plot("COGX","COGY","TelDeltaCOGPhi",ParisAnalysis::Event_PreSelected,false,"","","",ParisAnalysis::Tel_Selected,0);
add_telescope_scaled_plot("COGX","COGY","TelDeltaCOGR",ParisAnalysis::Event_Classified,false,"","","",ParisAnalysis::Tel_Selected,0);
add_telescope_scaled_plot("COGX","COGY","TelDeltaCOGPhi",ParisAnalysis::Event_Classified,false,"","","",ParisAnalysis::Tel_Selected,0);
add_telescope_scaled_plot("COGX","COGY","TelDeltaCOGR",ParisAnalysis::Event_GammaCandidate,false,"","","",ParisAnalysis::Tel_Selected,0);
add_telescope_scaled_plot("COGX","COGY","TelDeltaCOGPhi",ParisAnalysis::Event_GammaCandidate,false,"","","",ParisAnalysis::Tel_Selected,0);
add_tel_id_plot(5,0.5,5.5,ParisAnalysis::Event_Triggered);
add_tel_id_plot(5,0.5,5.5,ParisAnalysis::Event_Reconstructed);
add_tel_id_plot(5,0.5,5.5,ParisAnalysis::Event_PreSelected);
add_tel_id_plot(5,0.5,5.5,ParisAnalysis::Event_Classified);
add_tel_id_plot(5,0.5,5.5,ParisAnalysis::Event_GammaCandidate);
add_plot("MagneticFieldShowerDistance",180,0,180,ParisAnalysis::Event_Classified,"",0);
add_plot("MagneticFieldShowerDistance",180,0,180,ParisAnalysis::Event_GammaCandidate,"",0);
add_plot("MagneticFieldObservationDistance",180,0,180,ParisAnalysis::Event_Classified,"",0);
add_plot("MagneticFieldObservationDistance",180,0,180,ParisAnalysis::Event_GammaCandidate,"",0);
add_plot("MagneticFieldAzimut",180,0,180,ParisAnalysis::Event_Classified,"",0);
add_plot("MagneticFieldAzimut",180,0,180,ParisAnalysis::Event_GammaCandidate,"",0);
add_plot("MagneticFieldObservationDistance","MagneticFieldAzimut",18,0,180,180,0,180,ParisAnalysis::Event_Classified,"","",0);
add_plot("MagneticFieldObservationDistance","MagneticFieldAzimut",18,0,180,180,0,180,ParisAnalysis::Event_GammaCandidate,"","",0);
add_plot("MagneticFieldAzimut","DirectionError",18,0,180,50,0,0.1,ParisAnalysis::Event_Classified,"","",0);
add_plot("MagneticFieldAzimut","DirectionError",18,0,180,50,0,0.1,ParisAnalysis::Event_GammaCandidate,"","",0);
add_plot("TruePrimaryDepth","PrimaryDepth",60,-2,10,60,-2,10,ParisAnalysis::Event_Classified,"","",1);
add_plot("TruePrimaryDepth","PrimaryDepth",60,-2,10,60,-2,10,ParisAnalysis::Event_GammaCandidate,"","",1);
add_plot("TrueLogEnergy","LogEnergy",50,-2,3,50,-2,3,ParisAnalysis::Event_Classified,"","",1);
add_plot("TrueLogEnergy","LogEnergy",50,-2,3,50,-2,3,ParisAnalysis::Event_GammaCandidate,"","",1);
add_telescope_plot("TelLogCharge",200,-1,4,ParisAnalysis::Event_Reconstructed,false,"",ParisAnalysis::Tel_WData,1);
add_telescope_plot("TelLogCharge",200,-1,4,ParisAnalysis::Event_Classified,false,"",ParisAnalysis::Tel_Selected,1);
add_telescope_plot("TelNominalDistance",50,0,0.05,ParisAnalysis::Event_Reconstructed,false,"",ParisAnalysis::Tel_WData,1);
add_telescope_plot("TelNominalDistance",50,0,0.05,ParisAnalysis::Event_Classified,false,"",ParisAnalysis::Tel_Selected,1);
add_telescope_plot("TelLogCharge",200,-1,4,ParisAnalysis::Event_GammaCandidate,false,"",ParisAnalysis::Tel_Selected,1);
add_telescope_plot("TelLogShowerCharge",200,-1,4,ParisAnalysis::Event_Classified,false,"",ParisAnalysis::Tel_Selected,1);
add_telescope_plot("TelLogShowerCharge",200,-1,4,ParisAnalysis::Event_GammaCandidate,false,"",ParisAnalysis::Tel_Selected,1);
add_telescope_plot("TelLogCharge","TelLogShowerCharge",200,-1,4,200,1.5,4,ParisAnalysis::Event_Classified,false,"","",ParisAnalysis::Tel_Selected,1);
add_telescope_plot("TelLogCharge","TelLogShowerCharge",200,-1,4,200,1.5,4,ParisAnalysis::Event_GammaCandidate,false,"","",ParisAnalysis::Tel_Selected,1);
//===================
// = Maps = 
set_mapextension(2,2);
set_mapbinsize(0.02);
set_oversampling_size(0.1);
generate_acceptance(true);
use_radialacceptance(false);
use_zenithdependant_acceptance(true);
use_ring_backgroundmap(true,true,true);
use_adaptivering_backgroundmap(false);
use_template_background(true);
use_onoff_backgroundmap(false);
set_gradient_correction_max_angle(1.2);
set_gradient_correction_max_gradient(0.2);
//===================
// = Substractions = 
set_histotheta2max(0.1);
set_histotheta2nbins(60);
use_ring_background(true);
use_full_background(false);
use_gamma_fov_storage(true);
use_multipleoff_background(true);
multipleoff_background_optimize_regions(false);
multipleoff_background_normalizefullhisto(false);
multipleoff_background_exclude_onoff(true);
multipleoff_set_n_offregions(-1);
multipleoff_use_acceptance_gradient(true);
use_onoff_background(false);
//===================
// = Separation 
add_classification("ModelMono","MeanScaledShowerGoodness",ParisAnalysis::EventBit_GammaLike,-4,0.7);
add_classification("ModelMono","MeanScaledShowerGoodness",ParisAnalysis::EventBit_BackgroundLike,2,999);
add_rejection("ModelMono","PrimaryDepth",-1.1,1.3);
add_rejection("ModelMono","NSBGoodness",19,99999);
add_rejection("ModelMono","DirectionError",0,0.3);
run_singlerun_analysis(0.015,runno);
gApplication->Terminate(0);
}
EOF
root -q -b 'make_ModelPlus_Mono_Std_run.C({3})'
mkdir -p {5}
foreach file ( ./Results_ModelPlus_*_run*.root )
    cp ./$file {4}
end
